name: Report an issue with the package
description: Use GitHub Issues to report bugs only. For other questions, use GitHub Discussions.
body:
  - type: checkboxes
    id: dependencies
    attributes:
      label: Dependencies check up
      description: Before submitting an issue please make sure that you use latest version of all the package.
      options:
        - label: I have verified that I use latest version of all the package
          required: true
  - type: input
    id: version
    attributes:
      placeholder: 0.0.0
      label: What version of the package do you have in the package.json?
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of what the bug is and how to reproduce it
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Reproduction link
      placeholder: https://github.com/username/repository
      description: If possible, please provide a link to a repository or a codesandbox with a minimal reproduction of the bug.
  - type: textarea
    id: possibleFix
    attributes:
      label: Possible fix
      placeholder: I suggest fixing this bug by...
      description: If you have a suggestion on how to fix the bug, please describe it here
  - type: checkboxes
    id: self-service
    attributes:
      label: Self-service
      description: You are welcome to contribute to the library
      options:
        - label: I would be willing to implement a fix for this issue
